import type { Metadata } from "next";
import "../globals.css";
import { Jua } from "next/font/google";
import SideNavLeft from "@/components/public/SideNavLeft";
import SideNavRight from "@/components/public/SideNavRight";

const jua = Jua({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Kab Kab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jua.className}  antialiased`}>
        <div className="flex flex-row w-screen h-screen justify-between">
          <SideNavLeft />
          {children}
          <SideNavRight />
        </div>
      </body>
    </html>
  );
}
