import type { Metadata } from "next";
import "./globals.css";
import { Jua } from "next/font/google";
import SideNavLeft from "@/components/public/SideNavLeft";
import SideNavRight from "@/components/public/SideNavRight";
import { getServerSession } from "@/utils/auth";

const jua = Jua({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Kab Kab",
  description: "Generated by create next app",
  icons: "/kabkab.png",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${jua.className}  antialiased bg-white`}>
        <div className="flex ">
          <div className="flex-1 ml-1/5 mr-1/5 p-8 bg-white">{children}</div>
        </div>
      </body>
    </html>
  );
}
