import type { Metadata } from "next";
import "./globals.css";
import { Jua } from "next/font/google";
import SideNavLeft from "@/components/public/SideNavLeft";
import SideNavRight from "@/components/public/SideNavRight";
import { getServerSession } from "@/utils/auth";

const jua = Jua({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Kab Kab",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${jua.className}  antialiased bg-white`}>
        <div className="flex flex-row w-screen min-h-screen h-full justify-between">
          <SideNavLeft session={session} />
          {children}
          <SideNavRight />
        </div>
      </body>
    </html>
  );
}
