import type { Metadata } from "next";
import "../globals.css";
import { Jua } from "next/font/google";

const jua = Jua({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Kab Kab",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jua.className}  antialiased bg-white`}>
        <div className="flex flex-row w-screen min-h-screen h-full justify-between">{children}</div>
      </body>
    </html>
  );
}
